

ALTER TABLE Users
ALTER COLUMN Using_Solution NVARCHAR(255) NULL;

SELECT * FROM UserScores

DELETE FROM Users WHERE Id>=154
DELETE FROM UserScores WHERE id>=456

SELECT Email FROM Users WHERE Id = 157

ALTER TABLE Users
DROP COLUMN Last_Page;