CREATE TABLE users (
    id INT IDENTITY(1,1) PRIMARY KEY ,
    Name NVARCHAR(255) NOT NULL,
    Industry NVARCHAR(255) NOT NULL, 
    Country NVARCHAR(255) NOT NULL,
    Internal_Audit NVARCHAR(255) NOT NULL,
    Company_Size VARCHAR(255) NOT NULL, 
    Using_Solution NVARCHAR(255) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    Score INT
);

ALTER TABLE users
ADD Company_Size VARCHAR(255) NOT NULL

DROP TABLE users

SELECT * FROM Customers;
SELECT * FROM users


SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'users' AND COLUMN_NAME = 'Using_Solution';

SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'users' AND COLUMN_NAME = 'Using_Solution';



SELECT name, collation_name 
FROM sys.columns 
WHERE object_id = OBJECT_ID('users') AND name = 'Using_Solution';




ALTER TABLE users
ADD Using_Solution VARCHAR(255);


ALTER TABLE users 
ADD email NVARCHAR(255) NOT NULL UNIQUE;

CREATE TABLE industries(
    id INT PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL UNIQUE,
);

CREATE TABLE Countries(
    id INT PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL UNIQUE,
);

ALTER TABLE users
ADD country_id INT FOREIGN KEY REFERENCES Countries(id);

INSERT INTO industries (id, Name) VALUES
(1, 'Agriculture'),
(2, 'Automotive'),
(3, 'Banking'),
(4, 'Construction'),
(5, 'Education'),
(6, 'Energy'),
(7, 'Entertainment'),
(8, 'Finance'),
(9, 'Healthcare'),
(10, 'Hospitality'),
(11, 'Insurance'),
(12, 'IT'),
(13, 'Legal'),
(14, 'Manufacturing'),
(15, 'Marketing'),
(16, 'Media'),
(17, 'Pharmaceuticals'),
(18, 'Real Estate'),
(19, 'Retail'),
(20, 'Telecommunications'),
(21, 'Tourism'),
(22, 'Transportation'),
(23, 'Utilities'),
(24, 'Aerospace'),
(25, 'Biotechnology'),
(26, 'Chemicals'),
(27, 'Consumer Goods'),
(28, 'Electronics'),
(29, 'Fashion'),
(30, 'Food and Beverage'),
(31, 'Gaming'),
(32, 'Government'),
(33, 'Health and Wellness'),
(34, 'Human Resources'),
(35, 'Legal Services'),
(36, 'Logistics'),
(37, 'Mining'),
(38, 'Music'),
(39, 'Non-Profit'),
(40, 'Petroleum'),
(41, 'Publishing'),
(42, 'Real Estate Development'),
(43, 'Renewable Energy'),
(44, 'Sports'),
(45, 'Technology'),
(46, 'Television'),
(47, 'Travel'),
(48, 'Veterinary'),
(49, 'Waste Management'),
(50, 'Water Treatment');


SELECT * FROM industries ORDER BY id

INSERT INTO Countries (id, Name) VALUES
(1, 'Afghanistan'),
(2, 'Albania'),
(3, 'Algeria'),
(4, 'Andorra'),
(5, 'Angola'),
(6, 'Antigua and Barbuda'),
(7, 'Argentina'),
(8, 'Armenia'),
(9, 'Australia'),
(10, 'Austria'),
(11, 'Azerbaijan'),
(12, 'Bahamas'),
(13, 'Bahrain'),
(14, 'Bangladesh'),
(15, 'Barbados'),
(16, 'Belarus'),
(17, 'Belgium'),
(18, 'Belize'),
(19, 'Benin'),
(20, 'Bhutan'),
(21, 'Bolivia'),
(22, 'Bosnia and Herzegovina'),
(23, 'Botswana'),
(24, 'Brazil'),
(25, 'Brunei'),
(26, 'Bulgaria'),
(27, 'Burkina Faso'),
(28, 'Burundi'),
(29, 'Cabo Verde'),
(30, 'Cambodia'),
(31, 'Cameroon'),
(32, 'Canada'),
(33, 'Central African Republic'),
(34, 'Chad'),
(35, 'Chile'),
(36, 'China'),
(37, 'Colombia'),
(38, 'Comoros'),
(39, 'Congo (Congo-Brazzaville)'),
(40, 'Congo (Democratic Republic)'),
(41, 'Costa Rica'),
(42, 'Croatia'),
(43, 'Cuba'),
(44, 'Cyprus'),
(45, 'Czech Republic'),
(46, 'Denmark'),
(47, 'Djibouti'),
(48, 'Dominica'),
(49, 'Dominican Republic'),
(50, 'Ecuador'),
(51, 'Egypt'),
(52, 'El Salvador'),
(53, 'Equatorial Guinea'),
(54, 'Eritrea'),
(55, 'Estonia'),
(56, 'Eswatini'),
(57, 'Ethiopia'),
(58, 'Fiji'),
(59, 'Finland'),
(60, 'France'),
(61, 'Gabon'),
(62, 'Gambia'),
(63, 'Georgia'),
(64, 'Germany'),
(65, 'Ghana'),
(66, 'Greece'),
(67, 'Grenada'),
(68, 'Guatemala'),
(69, 'Guinea'),
(70, 'Guinea-Bissau'),
(71, 'Guyana'),
(72, 'Haiti'),
(73, 'Honduras'),
(74, 'Hungary'),
(75, 'Iceland'),
(76, 'India'),
(77, 'Indonesia'),
(78, 'Iran'),
(79, 'Iraq'),
(80, 'Ireland'),
(81, 'Israel'),
(82, 'Italy'),
(83, 'Jamaica'),
(84, 'Japan'),
(85, 'Jordan'),
(86, 'Kazakhstan'),
(87, 'Kenya'),
(88, 'Kiribati'),
(89, 'Kuwait'),
(90, 'Kyrgyzstan'),
(91, 'Laos'),
(92, 'Latvia'),
(93, 'Lebanon'),
(94, 'Lesotho'),
(95, 'Liberia'),
(96, 'Libya'),
(97, 'Liechtenstein'),
(98, 'Lithuania'),
(99, 'Luxembourg'),
(100, 'Madagascar'),
(101, 'Malawi'),
(102, 'Malaysia'),
(103, 'Maldives'),
(104, 'Mali'),
(105, 'Malta'),
(106, 'Marshall Islands'),
(107, 'Mauritania'),
(108, 'Mauritius'),
(109, 'Mexico'),
(110, 'Micronesia'),
(111, 'Moldova'),
(112, 'Monaco'),
(113, 'Mongolia'),
(114, 'Montenegro'),
(115, 'Morocco'),
(116, 'Mozambique'),
(117, 'Myanmar (Burma)'),
(118, 'Namibia'),
(119, 'Nauru'),
(120, 'Nepal'),
(121, 'Netherlands'),
(122, 'New Zealand'),
(123, 'Nicaragua'),
(124, 'Niger'),
(125, 'Nigeria'),
(126, 'North Korea'),
(127, 'North Macedonia'),
(128, 'Norway'),
(129, 'Oman'),
(130, 'Pakistan'),
(131, 'Palau'),
(132, 'Panama'),
(133, 'Papua New Guinea'),
(134, 'Paraguay'),
(135, 'Peru'),
(136, 'Philippines'),
(137, 'Poland'),
(138, 'Portugal'),
(139, 'Qatar'),
(140, 'Romania'),
(141, 'Russia'),
(142, 'Rwanda'),
(143, 'Saint Kitts and Nevis'),
(144, 'Saint Lucia'),
(145, 'Saint Vincent and the Grenadines'),
(146, 'Samoa'),
(147, 'San Marino'),
(148, 'Sao Tome and Principe'),
(149, 'Saudi Arabia'),
(150, 'Senegal'),
(151, 'Serbia'),
(152, 'Seychelles'),
(153, 'Sierra Leone'),
(154, 'Singapore'),
(155, 'Slovakia'),
(156, 'Slovenia'),
(157, 'Solomon Islands'),
(158, 'Somalia'),
(159, 'South Africa'),
(160, 'South Korea'),
(161, 'South Sudan'),
(162, 'Spain'),
(163, 'Sri Lanka'),
(164, 'Sudan'),
(165, 'Suriname'),
(166, 'Sweden'),
(167, 'Switzerland'),
(168, 'Syria'),
(169, 'Taiwan'),
(170, 'Tajikistan'),
(171, 'Tanzania'),
(172, 'Thailand'),
(173, 'Timor-Leste'),
(174, 'Togo'),
(175, 'Tonga'),
(176, 'Trinidad and Tobago'),
(177, 'Tunisia'),
(178, 'Turkey'),
(179, 'Turkmenistan'),
(180, 'Tuvalu'),
(181, 'Uganda'),
(182, 'Ukraine'),
(183, 'United Arab Emirates'),
(184, 'United Kingdom'),
(185, 'United States'),
(186, 'Uruguay'),
(187, 'Uzbekistan'),
(188, 'Vanuatu'),
(189, 'Vatican City'),
(190, 'Venezuela'),
(191, 'Vietnam'),
(192, 'Yemen'),
(193, 'Zambia'),
(194, 'Zimbabwe');

SELECT * FROM Countries
